//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RealtimeDashboard.Core.ServiceBus.Protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EntityEvent")]
  public partial class EntityEvent : global::ProtoBuf.IExtensible
  {
    public EntityEvent() {}
    
    private EntityEvent.EntityEventType _EventType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"EventType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public EntityEvent.EntityEventType EventType
    {
      get { return _EventType; }
      set { _EventType = value; }
    }
    private long _EntityId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"EntityId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long EntityId
    {
      get { return _EntityId; }
      set { _EntityId = value; }
    }
    private string _EntityType;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"EntityType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string EntityType
    {
      get { return _EntityType; }
      set { _EntityType = value; }
    }
    private readonly global::System.Collections.Generic.List<RelatedEntityInfo> _RelatedEntityInfo = new global::System.Collections.Generic.List<RelatedEntityInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"RelatedEntityInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<RelatedEntityInfo> RelatedEntityInfo
    {
      get { return _RelatedEntityInfo; }
    }
  
    private long _EventTime;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"EventTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long EventTime
    {
      get { return _EventTime; }
      set { _EventTime = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"EntityEventType")]
    public enum EntityEventType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNKNWON", Value=0)]
      UNKNWON = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ADD", Value=1)]
      ADD = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UPDATE", Value=2)]
      UPDATE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DELETE", Value=3)]
      DELETE = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RelatedEntityInfo")]
  public partial class RelatedEntityInfo : global::ProtoBuf.IExtensible
  {
    public RelatedEntityInfo() {}
    
    private long _EntityId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"EntityId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long EntityId
    {
      get { return _EntityId; }
      set { _EntityId = value; }
    }
    private string _TypeName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"TypeName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string TypeName
    {
      get { return _TypeName; }
      set { _TypeName = value; }
    }
    private string _RelationName;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"RelationName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string RelationName
    {
      get { return _RelationName; }
      set { _RelationName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}